package com.flowna.app.user;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.flowna.app.Chat.Chat;
import com.flowna.app.Report.v1.Report;
import com.flowna.app.ReviewSession.v1.ReviewSession;
import com.flowna.app.ScrumBoard.board.Scrumboard;
import com.flowna.app.Tracking.Tracking;
import com.flowna.app.Tracking.tag.Tag;
import com.flowna.app.deck.v1.Deck;
import com.flowna.app.studySquad.Room.Archived.ArchievedRoom;
import com.flowna.app.studySquad.Room.Room;
import com.flowna.app.studySquad.RoomMessage.RoomMessage;
import com.flowna.app.studySquad.RoomStudentScore.RoomStudentScore;
import com.flowna.app.studySquad.StudentAnswer.StudentAnswer;
import com.flowna.app.token.Token;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;


@Data
@EqualsAndHashCode(exclude = {"scrumboards","chats", "rooms"})
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "_user")
@Schema(description = "User entity")
public class User implements UserDetails {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;
  @Schema(description = "Firstname of the user", example = "Osama")
  @Column
  private String firstname;
  @Schema(description = "Lastname of the user", example = "Abdellatif")
  @Column
  private String lastname;

  @Column
  private String uniqueName;

  @Schema(description = "Unique email, can't be null", example = "example@gmail.com")
  @Column(unique = true,nullable = false)
  private String email;

  @Schema(description = "Used for study squad feature", example = "2000")
  @Column(nullable = false)
  private int studySquadTotalScore;

  @Schema(description = "Password for the account, can't be null, should be at lear 8 characters and with special signs , lower-upper case", example = "Test#32456")
  @Column(nullable = false)
  private String password;

  @Schema(description = "Boolean Variable set by server if the account is verfied using 2FA email or not", example = "true or false")
  @Column
  private boolean verified;
  @Schema(description = "Code generated from server to verify account", example = "")
  @Column
  private String message2FA;
  @Schema(description = "Code generated by Server to reset password for an account", example = "")
  @Column
  private String resetPassword;
  @Schema(description = "Role set by server and depends on the tier of the user", example = "freemium / premium")
  @Enumerated(EnumType.STRING)
  private Role role;

  @Column(nullable = true)
  private String profile_img;
  @Column(nullable = false)
  private int free_credits;
  @Column(nullable = false)
  private int paid_credits;
  @Column
  private boolean subscribed;
  @Column
  private LocalDate end_free_subscription;

  @CreationTimestamp
  @Column(updatable = false)
  private LocalDateTime joined_at;

  @CreationTimestamp
  @Column
  private LocalDateTime updates_at;


  @Schema(description = "Each user has many tokens in the DB, with one is just not expired !", example = "")
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
  private List<Token> tokens;


  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
  private List<ArchievedRoom> archievedRooms;

  @OneToOne(mappedBy = "user", cascade = CascadeType.ALL)
  private UserPreferences userPreferences;

  @JsonIgnore
  @OneToMany(mappedBy = "user", cascade = CascadeType.ALL,fetch = FetchType.LAZY)
  private List<Deck> decks;


  @JsonIgnore
  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
  Set<ReviewSession> reviewSessions = new HashSet<>();

  @JsonIgnore
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  List<Report> reports;

  @JsonIgnore
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  Set<Tracking> trackings = new HashSet<>();

  @JsonIgnore
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  Set<Tag> tags = new HashSet<>();



@ManyToMany(fetch = FetchType.LAZY)
@JoinTable(
        name = "room_user",
        joinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"),
        inverseJoinColumns = @JoinColumn(name = "room_id", referencedColumnName = "id"))
@JsonIgnore
private Set<Room> rooms = new HashSet<>();




@JsonIgnore
@ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "user_scrumboard",
            joinColumns = @JoinColumn(
                    name = "user_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(
                    name = "board_id", referencedColumnName = "id"))
  Set<Scrumboard> scrumboards = new HashSet<>();


  @JsonIgnore
  @ManyToMany(mappedBy = "users")
  private Set<Chat> chats = new HashSet<>();

  @JsonIgnore
  @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  private Set<StudentAnswer> studentAnswers = new HashSet<>();

  @JsonIgnore
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
  private Set<RoomMessage> roomMessages = new HashSet<>();


    @JsonIgnore
    @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Set<RoomStudentScore> scores = new HashSet<>();


  @PrePersist
    private void prePersist() {
        if (this.role == null) {
        this.role = Role.USER; // Default role if not set
        }
        if (this.free_credits < 0) {
        this.free_credits = 0; // Ensure free credits are not negative
        }
        if (this.paid_credits < 0) {
        this.paid_credits = 0; // Ensure paid credits are not negative
        }

        // Assign a unique username if not set
        if (this.uniqueName == null || this.uniqueName.trim().isEmpty()) {
          String baseUsername = (this.firstname != null ? this.firstname : "user") + (this.lastname != null ? this.lastname : "");
          baseUsername = baseUsername.replaceAll("\\s+", "").toLowerCase();
          String uniqueSuffix = java.util.UUID.randomUUID().toString().substring(0, 8);
          this.uniqueName = baseUsername + "_" + uniqueSuffix;
        }

    }

  @Override
  public Collection<? extends GrantedAuthority> getAuthorities() {
    return role.getAuthorities();
  }

  @Override
  public String getPassword() {
    return password;
  }

  @Override
  public String getUsername() {
    return email;
  }





  @Override
  public boolean isAccountNonExpired() {
    return true;
  }

  @Override
  public boolean isAccountNonLocked() {
    return true;
  }

  @Override
  public boolean isCredentialsNonExpired() {
    return true;
  }

  @Override
  public boolean isEnabled() {
    return true;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    User user = (User) o;
    return Objects.equals(id, user.id);
  }

}
