package com.flowna.app.studySquad;

public enum EventType {

    NEW_USER_JOINED,
    ROOM_MEMBERS_LIST,
    JOIN_ROOM,
    PLAYER_READY,
    TIMER_STARTED,
    TIMER_STOPED,
    SEND_MESSAGE,
    USER_LEFT,
    GET_ALL_MESSAGES,
    ROOM_SESSIONS,
    SET_ROOM_HOURS_GOAL,
    SET_DISCORD_LINK,
    USER_TYPING,
    UPDATE_LECTURE_LIST,
    EXAM_STARTED,
    EXAM_FINISHED,
    EXAM_IS_NOT_GOING,
    ROOM_SESSION_TIME_UPDATE,
    ERROR
}
